import type { Page, GhlPipeline, GhlIntegration } from "@/types/prd";

export function defaults(): Page[] {
  return [
    { id:"home", label:"Home", nav:true, parent:null, blocks:[
      { type:"hero", title:"Hero Section", desc:"The world of Denim City. No routing, no choice — everyone sees the same place. Reference model: Vitra Campus, Design Museum London, MSI Chicago.", content:["Headline: short, punchy line positioning Denim City as a denim innovation hub","Subline: 'Towards a Brighter Blue'","Visual: full-width image or video of the location — the space, the machines, the people","No routing buttons. The homepage is for everyone. Navigation is organized by activity (Store, Education, Lab, Tours, etc.). B2C/B2B overview pages exist as separate landing pages, reachable via CTA and footer."], annotations:[{team:"design",text:"No stock photos. Use real images of the location, the team, the work. The hero must feel like arriving at the building."},{team:"design",text:"Reference: Vitra Campus homepage — the place as a whole, not the services."},{team:"dev",text:"No conditional content. No cookies or sessions for routing. The homepage is static for all visitors."}] },
      { type:"grid", title:"The Place", desc:"What Denim City is — all facets in one overview. Not split by audience.", content:["Store: strictly offline denim retail","Lab & Atelier: the only sustainable laundry lab in the Netherlands","Education: Academy, Incubator, Jean School","Tours: see where your jeans come from","Collaborate: partnerships, collabs, funding","Each tile: image + short text. No CTA per tile — the navigation points the way."], annotations:[{team:"design",text:"Asymmetric tiles. Not everything the same size. Show the diversity of the place, not a product catalog."},{team:"dev",text:"Static grid. No conditional rendering. Each tile links to the corresponding section in the navigation."}] },
      { type:"section", title:"Agenda / Upcoming", desc:"Next upcoming events, Friday Talks, courses.", content:["Show max 3 items","No dedicated page, section on home only","Footer link to full overview (TBD)"], annotations:[{team:"ghl",text:"GHL CALENDARS: Pull events and courses from GHL calendar via API. Booking link → GHL funnel per event type."},{team:"dev",text:"GHL Calendar API endpoint required. Fallback: static content if API unavailable."}] },
      { type:"section", title:"Social Proof / Press", desc:"Short block with media mentions, figures, or quotes.", content:["NY Times mention (2012), I Amsterdam listing (goal)","Figures: 57 incubator talents, 550+ worldwide, 95% progression","Quote from Mariette or tour feedback"], annotations:[{team:"design",text:"Not a testimonial carousel. Integrate into the page as a typographic element."}] },
      { type:"grid", title:"Published Articles", desc:"Articles and media features about Denim City, House of Denim, and the team.", content:["Show latest 3–6 articles as cards: thumbnail, title, source, date","Sources: NY Times, I Amsterdam, industry publications, own blog","Link to full Press page for complete archive","Each card links to the original article (external)"], annotations:[{team:"dev",text:"CMS-driven. Each article: title, source name, date, thumbnail, external URL. Sort by date descending."},{team:"design",text:"Editorial card layout. Source logo or name prominent. Not a blog feed — curated highlights."}] },
      { type:"cta", title:"Footer CTA", desc:"Universal conversion section at bottom of every page.", content:["'Plan your visit' or 'Book a tour' — context-dependent","Contact form or booking link","Always visible, always the same structure"], annotations:[{team:"ghl",text:"GHL FORM: Universal contact form → GHL via Webflow webhook. Tagging based on page origin for correct pipeline assignment."}] },
    ]},
    { id:"individuals", label:"Individuals", nav:true, parent:"home", blocks:[
      { type:"hero", title:"For Individuals", desc:"Overview page for consumers, denim enthusiasts, and visitors. Not in the main navigation — reachable via homepage CTA and footer.", content:["Everything you can do at Denim City as an individual","No sales pitch — let the experience speak","Tone of voice: inviting, personal, discovery-oriented"], annotations:[{team:"design",text:"Warm, accessible. Reference: 'Private Customers' at Vitra, 'Explore' at MSI Chicago."},{team:"dev",text:"Reachable via homepage CTA ('See what's here for you') and footer. Not in the main navigation."}] },
      { type:"grid", title:"Shop", desc:"The physical store — strictly offline.", content:["6-meter Jeans Wall: the best denim brands","Fabric Wall: fabrics by the meter for makers","Collabs and limited editions","Link → Store page"], annotations:[] },
      { type:"grid", title:"Learn", desc:"Courses and workshops for everyone.", content:["Make Your Own Jeans, Bag, Jacket, Kimono","Customize, Sashiko, Repair, Denim 101","Link → Education > Academy"], annotations:[] },
      { type:"grid", title:"Visit", desc:"Tours, events, and experiencing the place.", content:["Tours: see where your jeans come from (€250 educational)","Agenda: Friday Talks, workshops, open days","Link → Tours page"], annotations:[] },
      { type:"grid", title:"Services", desc:"Repair, customization, made to order.", content:["Repair: free for Nudie, dedicated partner for KOI","Customization: patches, upgrades, personalization","Made to Order: bespoke by Incubator talent","Hemming: chain stitching","Link → Store > Repair & Customization / Made to Order"], annotations:[] },
      { type:"cta", title:"Footer CTA", desc:"'Plan your visit' — universal CTA.", content:["Book a tour, plan your visit, or get in touch"], annotations:[{team:"ghl",text:"GHL FORM: Contact form → GHL. Tag as B2C via page origin."}] },
    ]},
    { id:"companies", label:"Companies & Schools", nav:true, parent:"home", blocks:[
      { type:"hero", title:"For Companies & Schools", desc:"Overview page for B2B: brands, labels, schools, companies. Not in the main navigation — reachable via homepage CTA and footer.", content:["What Denim City can do for your organization","Professional, but not corporate — the place takes center stage","Tone of voice: business-oriented, concrete, collaboration-focused"], annotations:[{team:"design",text:"Professional but warm. Reference: 'Business Clients' at Vitra, 'Corporate' at Design Museum London."},{team:"dev",text:"Reachable via homepage CTA and footer. Not in the main navigation."}] },
      { type:"grid", title:"Lab & Atelier", desc:"Sustainable laundry, prototyping, capsule production.", content:["Sustainable Laundry R&D","Prototype & Sample Development","Capsule Collections","Custom Made Products","Link → Lab & Atelier page"], annotations:[] },
      { type:"grid", title:"Education & Talent", desc:"Academy B2B, Incubator, Jean School.", content:["Academy B2B: team building workshops, custom programs for schools & companies","Incubator talent: hire for production, workshops, launches","Jean School: curriculum collaboration","Link → Education page"], annotations:[] },
      { type:"grid", title:"Partnerships & Collabs", desc:"Collaborate with Denim City.", content:["Collabs: co-branded projects (Lycra, KOI, Denham)","Partnerships: structural, often in-kind (Oficina, MIC, APXpress, Jeanologia)","Funding: House of Denim Foundation","Partnership packages: €1,000 / €5,000+ / €15-20K","Link → Collaborate page"], annotations:[] },
      { type:"grid", title:"Tours & Venue", desc:"Corporate tours and venue rental.", content:["Tours: €500 commercial, team outings, corporate visits","Venue Rental: archive space €2,000 base, events","Link → Tours / Venue Rental pages"], annotations:[] },
      { type:"cta", title:"Footer CTA", desc:"'Let's talk' — B2B contact CTA.", content:["Contact form with dropdown: what's your inquiry?","Link to Contact page with correct pre-selection"], annotations:[{team:"ghl",text:"GHL FORM: Contact form → GHL. Tag as B2B via page origin. Smart routing to correct pipeline."}] },
    ]},
    { id:"store", label:"Store", nav:true, parent:null, blocks:[
      { type:"hero", title:"Store Hero", desc:"'STRICTLY OFFLINE — Some things you have to see for yourself.'", content:["No webshop. No product pages with 'add to cart'.","Hero communicates the physical experience.","CTA: 'Visit us' with opening hours + address"], annotations:[{team:"design",text:"This is the page where the 'strictly offline' positioning must come through strongest."},{team:"dev",text:"Google Maps embed with custom styling. Opening hours as structured data (Schema.org LocalBusiness)."}] },
      { type:"grid", title:"Brands", desc:"Denim brands and independent designers carried in-store.", content:["Denim brands: Benzak, Edwin, KOI, Kuyichi, Nudie, Naked and Famous","Independent designers: Jouez les Enfants, Florian Regtien, Peter Wertmann, Jan de Vries, Wallflower","6-meter Jeans Wall: pairs of jeans on display, brands explained","No brand logo grid — each brand deserves context and story"], annotations:[{team:"design",text:"No brand logo grid. Each brand deserves context."},{team:"dev",text:"CMS-driven content so brands can be easily added/removed."}] },
      { type:"section", title:"Collabs", desc:"Limited editions and collaborative products available in-store.", content:["Very GoodS Studio (candles)","Mood Denim (spray)","Royal Delft x Henk Schiffmacher","Rotating selection — highlight what's current"], annotations:[{team:"design",text:"Collabs should feel special and limited. Not a regular product listing."},{team:"dev",text:"CMS-driven so collabs can be swapped seasonally."}] },
      { type:"section", title:"Fabrics", desc:"Fabric Wall — fabric by the meter for makers and designers.", content:["Fabric Wall: raw selvedge to innovative stretch","Sold by the meter — for makers, designers, and studios","Sourcing: Japanese selvedge, Italian stretch, organic cotton, deadstock","Not a webshop-style listing. Mood images + short description."], annotations:[{team:"design",text:"Tactile, material-focused. Show texture, weight, weave."}] },
      { type:"section", title:"Repair & Customization", desc:"Services to extend and personalize denim.", content:["Repair: 'Free repair for life' partner for Nudie. Dedicated partner for KOI.","Customization: upgrades, patches, personalization","Hemming: genuine chain stitching","Walk-in or by appointment"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Repair B2B': For brand partnership inquiries. Webflow form → GHL pipeline with auto-tagging."},{team:"ghl",text:"GHL BOOKING: Repair/customization appointments via Calendly → GHL. Confirmation + reminder automated."},{team:"dev",text:"Own CTA with booking link."}] },
      { type:"section", title:"Made to Order", desc:"Tailor-made jeans crafted by Incubator talent.", content:["Bespoke jeans: choose fabric, fit, details","Made by Incubator talent on-site","Process: consultation → measurement → production → fitting","Turnaround and pricing TBD from Milene"], annotations:[{team:"design",text:"Premium feel. This is the top-tier service offering."},{team:"dev",text:"Separate intake form with measurement fields. Dedicated CTA."}] },
    ]},
    { id:"education", label:"Education", nav:true, parent:null, blocks:[
      { type:"hero", title:"Education", desc:"All learning programs under the Denim City and House of Denim umbrella.", content:["Three pillars: Academy (courses), Incubator (talent development), Jean School (degree programs)","Supporting resources: Archive and Library","Audiences: B2C (consumers, enthusiasts) and B2B (brands, schools, companies)"], annotations:[{team:"design",text:"Education landing page — route visitors to the right program. Not a course catalog."},{team:"dev",text:"Routing or tabs for B2C / B2B audiences."}] },
      { type:"grid", title:"Academy", desc:"Denim City Academy by House of Denim — courses for B2C and B2B.", content:["B2C: Make Your Own Jeans ⭐, Customize Your Jeans, Make Your Own Bag, Sashiko, Denim 101","B2B: Team building workshops, custom programs for schools & companies","Full list: Jeans, Jacket, Kimono, Bag, Customize/Upcycle, Sashiko, Repair, Denim 101, eDesigner","Schools: Summer/Winter School, Custom programs"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Courses': Every booking → pipeline. Automations: confirmation, reminder, post-course feedback + upsell (30d)."},{team:"ghl",text:"GHL ABANDONED BOOKING: Recovery sequence at 1h, 24h, 72h."},{team:"dev",text:"Filter by B2C/B2B audience. Pricing from Milene needed — placeholder."}] },
      { type:"section", title:"Incubator", desc:"By House of Denim — a modern guild for denim talent. B2C and B2B tracks.", content:["B2C: 57 talents, ~8 daily on-site, 550+ worldwide, 95% progression","Guild model: Intern → Trial → Incubator","Roles: repair specialists, wash masters, made-to-order designers, teachers, retail, micro-entrepreneurs","B2B: Small productions, capsule collections, workshops, launches, trade shows","Application: CV, portfolio, motivation, trial day(s)"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Incubator': Application → review → trial day → acceptance. Longest pipeline."},{team:"design",text:"Numbers prominent but not as infographic. Integrate into the story."}] },
      { type:"section", title:"Jean School", desc:"We are cofounders. We wrote the curriculum. We are the location.", content:["3-year Dutch + 1-year International program","Only school: store in front, lab in back, school upstairs","Revenue: rent + curriculum licensing fee","Cross-sell: 'Don't want 3 or 1 year? Book a Denim City Academy course.'"], annotations:[{team:"dev",text:"Do NOT become their marketing department. Link to jeanschool.com. External link, opens in new tab."},{team:"design",text:"Single section, compact. Positions our role, not their offering."}] },
      { type:"section", title:"Archive", desc:"Denim City's physical denim archive — a research and inspiration resource.", content:["Historical denim pieces and reference garments","Available for research visits, brand consultations, and educational programs","By appointment"], annotations:[{team:"design",text:"Reverent, museum-like. Show the depth of the collection."}] },
      { type:"section", title:"Library", desc:"Curated denim and textile library on-site.", content:["Books, magazines, and reference materials on denim, textiles, and fashion","Open to visitors, students, and researchers","Complements the Archive and Academy programs"], annotations:[{team:"design",text:"Warm, inviting. Not a dusty shelf — a living resource."}] },
    ]},
    { id:"lab", label:"Lab & Atelier", nav:true, parent:null, blocks:[
      { type:"hero", title:"Lab & Atelier", desc:"'The only lab in the Netherlands.' Sustainable Laundry Lab + Atelier production.", content:["Positioning: 'Only lab in the Netherlands / Northern mainland Europe'","Visuals: the machines, the work, the wash results","Equipment: Laser (Jeanologia eDesigner), Ozone, EcoStone, Natural dyes, Coatings","Rigmic Partnership: washmaster Pauline, 'premier league' lab"], annotations:[{team:"design",text:"Industrial, but not 'factory'. Lab feel: clean, innovative, precision."},{team:"design",text:"Show equipment visually, not as a bullet list."}] },
      { type:"section", title:"Sustainable Laundry R&D", desc:"Research and development for sustainable wash and finish techniques.", content:["Ozone washing, EcoStone, natural dyes, low-water processes","Developing new sustainable alternatives for conventional finishing","Collaboration with brands and researchers on innovation projects","Testing and validation for new wash recipes"], annotations:[{team:"design",text:"Science meets craft. Show the R&D process, not just the results."},{team:"ghl",text:"GHL PIPELINE 'Lab/Atelier': R&D inquiries → intake form → project scoping."}] },
      { type:"section", title:"Prototype & Sample Development", desc:"From sketch to sample — rapid prototyping for brands and designers.", content:["Pattern making, first samples, fit iterations","Wash development and sample washings","Small-batch testing before committing to production","Team: Jos (master tailor), Jan de Vries, Incubator talent"], annotations:[{team:"dev",text:"Own CTA with intake form. Separate from production inquiries."},{team:"ghl",text:"GHL: Prototype inquiries → Lab/Atelier pipeline with 'prototype' tag."}] },
      { type:"section", title:"Capsule Collections", desc:"End-to-end capsule production up to ~100 pieces.", content:["From concept to finished collection","Fabric sourcing, pattern, production, wash & finish — all in-house","Ideal for independent labels and emerging designers","Industrial sewing machines + atelier capacity"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Lab/Atelier': Capsule inquiries → quote → project tracking."},{team:"design",text:"Show completed capsule projects as case studies."}] },
      { type:"section", title:"Made-to-Order", desc:"Bespoke garments for individuals and small orders.", content:["Tailor-made jeans, jackets, and custom pieces","Choose fabric, fit, details — made by Incubator talent on-site","Process: consultation → measurement → production → fitting"], annotations:[{team:"dev",text:"Separate intake form with measurement fields. Dedicated CTA."},{team:"design",text:"Premium, personal feel. This is the luxury tier."}] },
      { type:"section", title:"Custom Made Products", desc:"White-label and custom product development for brands and companies.", content:["Co-branded merchandise and custom denim products","Corporate gifts, event merchandise, branded workwear","From design to delivery — managed end-to-end","MOQ and pricing on inquiry"], annotations:[{team:"ghl",text:"GHL: Custom product inquiries → Lab/Atelier pipeline with 'custom' tag. B2B nurture sequence."},{team:"dev",text:"B2B inquiry form with project scope fields."}] },
    ]},
    { id:"tours", label:"Tours", nav:true, parent:null, blocks:[
      { type:"hero", title:"Tour Hero", desc:"'If you ever did a tour, you will never buy the same way again.'", content:["Two categories: Educational & NGO's / Companies","Pricing: €500 commercial, €250 educational","Direct booking CTA"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Tours': Booking → confirmation → reminder → post-tour nurture + upsell."},{team:"ghl",text:"GHL TOUR→COURSE CONVERSION: Auto email sequence after tour."}] },
      { type:"section", title:"What You'll See", desc:"Tour content without giving it away.", content:["Sustainability is cool, not boring","Circularity is practical","Value of product","Four guides: Jos (archive), Mariette (sustainability), Bowie (lab/wash), Jan (craftsmanship)"], annotations:[{team:"design",text:"Give a taste, not the full tour. Mood images only."}] },
      { type:"cta", title:"Booking", desc:"Direct booking flow.", content:["Calendly embed or custom booking form","Choice: Educational / Commercial","Date + group size"], annotations:[{team:"ghl",text:"Calendly → GHL: Sync booking data as contact properties."},{team:"dev",text:"Calendly inline embed with Denim City styling. No redirect."}] },
    ]},
    { id:"collaborate", label:"Collaborate", nav:true, parent:null, blocks:[
      { type:"hero", title:"Collaborate Hero", desc:"Three forms of collaboration, each with its own logic.", content:["Collabs: commercial partnerships (Lycra, KOI, Denham)","Partnerships: structural, often in kind (Oficina, MIC, APXpress, Jeanalogia)","Non-profit funding: House of Denim Foundation"], annotations:[{team:"design",text:"Three tracks visually distinct. Not three identical columns."}] },
      { type:"section", title:"Projects Showcase", desc:"Existing projects as social proof.", content:["Categories: Industry / Cultural / Private","Examples: Team NL Olympics x Denham, Amsterdam Museum, FLAX project","NRI 3001 NOT to be shown (NDA)"], annotations:[{team:"dev",text:"CMS-driven. Each project as case study card. Filterable by category."}] },
      { type:"section", title:"Partnership Packages", desc:"Tiers: €1,000 / €5,000+ / €15-20K.", content:["Transparency: show the value chain","Details from Milene needed"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Partnerships': Inquiry → discovery call → proposal. Long B2B nurture."}] },
      { type:"cta", title:"Funding / Support", desc:"Separate section for funders.", content:["PVH Foundation as reference (Commitment #9, D&I)","Sponsor deck: needs to be created","CTA: 'Talk to us about funding'"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Funding': Inquiry → application → reporting. Separate pipeline."}] },
    ]},
    { id:"about", label:"About / Story", nav:true, parent:null, blocks:[
      { type:"section", title:"Origin Story", desc:"Denim City timeline.", content:["2008: 'Something has to change. Why not Amsterdam?'","2010: First co-creation, House of Denim Foundation","2012: Jean School, NY Times","2014: Kingpins → Amsterdam","2015: Denim City in De Hallen","2022: Incubator Program","Future: São Paulo, Istanbul, Joburg"], annotations:[{team:"design",text:"Timeline not as vertical line with dots. Find a form that fits Denim City."}] },
      { type:"section", title:"Team", desc:"Who to feature.", content:["James Veenhof — Co-founder","Mariette Hoitink — Co-founder","Jos — Master tailor","The team"], annotations:[{team:"design",text:"Real portraits, in their element."}] },
      { type:"section", title:"House of Denim", desc:"The foundation behind Denim City.", content:["Non-profit foundation","Mission: 'Advocate the good, collaborate for the better, educate the best'","'Towards a Brighter Blue'","Cofounders of Jean School, creators of Denim City"], annotations:[] },
    ]},
    { id:"contact", label:"Contact", nav:true, parent:null, blocks:[
      { type:"section", title:"Contact Hub", desc:"One contact page, multiple entry points.", content:["Form with dropdown: what are you reaching out about?","Options: Store, Courses, Tours, Lab, Partnerships, Venue, Press, Incubator, Other","Based on choice: correct fields + correct GHL pipeline"], annotations:[{team:"ghl",text:"GHL SMART ROUTING: Form choice determines pipeline, tags, automation sequence. Webflow → GHL webhook."},{team:"ghl",text:"GHL PIPELINES: Tours, Courses, Lab/Atelier, Partnerships, Venue, Funding, Press, Incubator, Repair B2B."},{team:"dev",text:"Dynamic form: fields change on dropdown. Not 9 separate forms."}] },
    ]},
    { id:"venue", label:"Venue Rental", nav:false, parent:null, blocks:[
      { type:"hero", title:"Venue Rental", desc:"Landing page, not in main nav. 'Huge unmet demand.'", content:["Archive space: €2,000 base","Extras separate: cleaning, bar, catering, tech","Best model: collaboration with Hallen Studios"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Venue': Inquiry → availability → quote → contract. 48h follow-up."},{team:"dev",text:"Not in main nav. Footer + direct URL. SEO-optimize."}] },
    ]},
    { id:"press", label:"Press", nav:false, parent:null, blocks:[
      { type:"section", title:"Press Releases", desc:"Overview of all published press releases.", content:["Chronological list of press releases","Each release: title, date, summary, full text or PDF download","Filterable by year or topic"], annotations:[{team:"dev",text:"CMS-driven. Each press release as its own entry with date, title, and downloadable PDF."},{team:"design",text:"Clean, editorial layout. Date-stamped entries."}] },
      { type:"section", title:"Downloadable Imagery", desc:"Press-ready images and visual assets for media use.", content:["High-resolution photos: location, team, products, events","Logo pack: Denim City, House of Denim (various formats)","Brand guidelines and usage instructions","ZIP download per category or individual download"], annotations:[{team:"dev",text:"Hosted image gallery with download links. Consider ZIP bundles per category."},{team:"design",text:"Grid layout with preview thumbnails. Clear download buttons."}] },
      { type:"cta", title:"Press Inquiries", desc:"Contact point for media and press.", content:["Press inquiry form — name, outlet, topic, deadline","Direct email as fallback"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Press': Inquiry → follow-up. Simplest pipeline."}] },
    ]},
    { id:"saopaulo", label:"São Paulo", nav:false, parent:null, blocks:[
      { type:"section", title:"Denim City São Paulo", desc:"Separate section, not in main nav. Teaser on home.", content:["Location info, offerings, connection to Amsterdam","Brand guidelines with floor stickers"], annotations:[{team:"dev",text:"Not in main nav. Home teaser + footer."}] },
    ]},
  ];
}

export const GHL_PIPES: GhlPipeline[] = [
  { n: "Tours", t: "Booking/Calendly", a: "Confirmation, reminder, post-tour nurture, tour→course conversion" },
  { n: "Courses", t: "Booking/Calendly", a: "Confirmation, reminder, feedback, upsell (30d), abandoned recovery, certificate" },
  { n: "Lab/Atelier", t: "Inquiry form (3 tracks)", a: "Inquiry → quote → project tracking. Sub-flows per audience." },
  { n: "Partnerships", t: "Inquiry form", a: "Inquiry → discovery → proposal. Long B2B nurture." },
  { n: "Venue", t: "Inquiry form", a: "Inquiry → availability → quote → contract. 48h follow-up." },
  { n: "Funding", t: "Inquiry form", a: "Inquiry → application → reporting." },
  { n: "Press", t: "Inquiry form", a: "Inquiry → follow-up." },
  { n: "Incubator", t: "Application form", a: "Intake → review → trial day → acceptance." },
  { n: "Repair B2B", t: "Partnership inquiry", a: "Brand inquiry → discovery → onboarding." },
];

export const GHL_INT: GhlIntegration[] = [
  { s: "Lightspeed R", d: "→ GHL", p: "Store purchases → customer data + post-purchase nurture" },
  { s: "Webflow", d: "→ GHL", p: "All forms. Webhooks per form to correct pipeline." },
  { s: "Calendly", d: "→ GHL", p: "All bookings. Sync to GHL contacts + pipeline." },
];

export const UNIVERSAL_AUTOMATIONS = [
  "Booking confirmations + reminders (24h)",
  "Post-experience feedback",
  "Abandoned booking recovery (1h, 24h, 72h)",
  "Cross-sell sequences per service",
  "Certificate delivery (courses)",
  "B2C/B2B segmentation from homepage routing",
];
