import type { Page, GhlPipeline, GhlIntegration } from "@/types/prd";

export function defaults(): Page[] {
  return [
    { id:"home", label:"Home", nav:true, parent:null, blocks:[
      { type:"hero", title:"Hero Section", desc:"The world of Denim City. No routing, no choice — everyone sees the same place. Reference model: Vitra Campus, Design Museum London, MSI Chicago.", content:["Headline: short, punchy line positioning Denim City as a denim innovation hub","Subline: 'Towards a Brighter Blue'","Visual: full-width image or video of the location — the space, the machines, the people","No routing buttons. The homepage is for everyone. Navigation is organized by activity (Store, Education, Lab, Tours, etc.). Audience differentiation happens within each service page at the point of conversion (pricing tiers, CTAs)."], annotations:[{team:"design",text:"No stock photos. Use real images of the location, the team, the work. The hero must feel like arriving at the building."},{team:"design",text:"Reference: Vitra Campus homepage — the place as a whole, not the services."},{team:"dev",text:"No conditional content. No cookies or sessions for routing. The homepage is static for all visitors."}] },
      { type:"grid", title:"The Place", desc:"What Denim City is — all facets in one overview. Not split by audience.", content:["Store: strictly offline denim retail","Lab & Atelier: the only sustainable laundry lab in the Netherlands","Education: Academy, Incubator, Jean School","Tours: see where your jeans come from","Collaborate: partnerships, collabs, funding","Each tile: image + short text. No CTA per tile — the navigation points the way."], annotations:[{team:"design",text:"Asymmetric tiles. Not everything the same size. Show the diversity of the place, not a product catalog."},{team:"dev",text:"Static grid. No conditional rendering. Each tile links to the corresponding section in the navigation."}] },
      { type:"section", title:"Denim Dates / Upcoming", desc:"Teaser for the full Denim Dates page. Max 3 upcoming items.", content:["Show max 3 upcoming items from Denim Dates","Link to Denim Dates page for the complete overview","Pulls from the same data source as the full Denim Dates page"], annotations:[{team:"ghl",text:"GHL CALENDARS: Pull events and courses from GHL calendar via API. Booking link → GHL funnel per event type."},{team:"dev",text:"Same data source as Denim Dates page. Show next 3 items chronologically."}] },
      { type:"grid", title:"In the Press & In the Wild", desc:"Mixed-media grid of press coverage and curated third-party social posts. The world talking about Denim City — not Denim City talking about itself.", content:["Press clippings: newspaper scans, magazine spreads, online article screenshots, video/TV thumbnails","Curated social posts: visitor Instagram stories, student posts, brand tags, influencer mentions — hand-picked by the team, not a live feed","Key figures woven into the grid: 57 incubator talents, 550+ worldwide, 95% progression","Each item links to source: external article URL, original social post, or full Press page","Show 6–9 items on homepage, link to full Press page for archive"], annotations:[{team:"design",text:"This is a mood board, not a card grid. Embrace the mixed media — a yellowed NY Times clipping next to a crisp Dezeen screenshot next to someone's Instagram post next to a glossy magazine spread. The contrast IS the story. It says 'we've been around, and we're still relevant.' Each item keeps its native format: newspaper scan slightly rotated with paper texture/shadow (the age is the charm), magazine cover/spread shown as physical object with slight perspective, online articles as clean headline + source logo + date, video/TV as thumbnail with play indicator, social posts as embedded-style cards showing the original post format. Not uniform cards. Think press wall in a physical space."},{team:"dev",text:"CMS-driven. Each item: type (newspaper/magazine/online/video/social), title, source name, date, thumbnail/scan image, external URL, optional caption. Social posts are NOT live embeds — store as screenshot + link to original. Team curates manually. Sort by editorial weight, not just date."},{team:"dev",text:"Social posts: do NOT use Instagram/Twitter embed APIs (fragile, API changes, rate limits). Instead: screenshot + link to original post. The team adds posts to CMS when they find good ones. Content control stays with DC."}] },
      { type:"cta", title:"Footer CTA", desc:"Universal conversion section at bottom of every page.", content:["'Plan your visit' or 'Book a tour' — context-dependent","Contact form or booking link","Always visible, always the same structure"], annotations:[{team:"ghl",text:"GHL FORM: Universal contact form → GHL via Webflow webhook. Tagging based on page origin for correct pipeline assignment."}] },
    ]},
    { id:"denimdates", label:"Denim Dates", nav:true, parent:null, blocks:[
      { type:"hero", title:"Denim Dates", desc:"The Agenda is where visitors decide to actually do something — book a course, attend a Friday Talk, sign up for a workshop. Every other nav item (Store, Education, Lab, Tours) describes what Denim City is. The Agenda shows what's happening now. That's the difference between a brochure and a living place.", content:["Full calendar/agenda of everything happening at Denim City","Courses, workshops, Friday Talks, open days, exhibitions, pop-ups, launches","Filterable by type, date, audience","This page needs its own intelligent design — not a standard list or grid"], annotations:[{team:"design",text:"This page gets its own design. The Agenda is the heartbeat of Denim City — it must feel alive, dynamic, and inviting. Not a corporate event calendar. Reference: 'What's On' at Design Museum London, 'Events' at Vitra Campus. Think editorial, not spreadsheet."},{team:"design",text:"The Agenda is the most frequently revisited page. It should reward return visits — show what's new, what's soon, what's selling out."},{team:"dev",text:"SEO: Nav label is 'Denim Dates' (branded). Page <title> must be 'Denim Dates — Events & Workshops at Denim City Amsterdam'. H1: 'Denim Dates'. Meta description must contain: events, workshops, courses, agenda, Amsterdam. The branded term becomes searchable over time."},{team:"dev",text:"GHL Calendar API as data source. Each event: title, date/time, type (course/talk/event/exhibition), description, image, booking link, capacity/availability."}] },
      { type:"section", title:"Upcoming Highlights", desc:"Editorially curated top picks — not just chronological.", content:["Featured events: hand-picked by the team, large visual treatment","Next Friday Talk with speaker info and topic","Next workshop with spots remaining","Seasonal highlight: Summer School, exhibition opening, etc."], annotations:[{team:"design",text:"This section is editorial, not automated. Give it magazine-level attention. Large images, bold typography."},{team:"dev",text:"CMS-driven featured section. Staff picks override chronological order here."}] },
      { type:"grid", title:"Full Calendar", desc:"All events, filterable and browsable.", content:["Chronological list of all upcoming events","Filter by: Courses, Talks, Events, Exhibitions, Open Days","Filter by: This week / This month / All upcoming","Each card: date, title, type badge, short description, book button","Past events collapse or move to archive"], annotations:[{team:"design",text:"Dense but scannable. Date as the primary anchor. Type badges for quick recognition. Sold-out items greyed but visible (social proof)."},{team:"dev",text:"GHL Calendar API integration. Real-time availability. Booking link → GHL funnel per event type."},{team:"ghl",text:"GHL CALENDARS: Each event type maps to a pipeline. Booking → confirmation → reminder → post-event feedback. Abandoned booking recovery on courses."}] },
      { type:"section", title:"Recurring Programs", desc:"Things that happen regularly — not tied to a single date.", content:["Friday Talks: every Friday, rotating speakers and topics","Academy courses: ongoing enrollment, multiple dates per course","Incubator intake: application windows","Tours: available daily, book your slot"], annotations:[{team:"design",text:"Separate from the calendar. These are permanent fixtures, not one-off events. Treat them like program descriptions with a 'next date' indicator."},{team:"dev",text:"Link to respective pages (Education, Tours) for full details. Show next available date inline."}] },
      { type:"cta", title:"Stay Updated", desc:"Newsletter / notification signup for agenda updates.", content:["'Never miss what's happening' — email signup","Option to select interests: courses, talks, events, exhibitions","Weekly or monthly digest"], annotations:[{team:"ghl",text:"GHL FORM: Newsletter signup → GHL. Tag by interest selection. Automated weekly/monthly digest based on upcoming events."},{team:"dev",text:"Simple email + interest checkboxes. No account creation needed."}] },
    ]},
    { id:"store", label:"Store", nav:true, parent:null, blocks:[
      { type:"hero", title:"Store Hero", desc:"'STRICTLY OFFLINE — Some things you have to see for yourself.'", content:["No webshop. No product pages with 'add to cart'.","Hero communicates the physical experience.","CTA: 'Visit us' with opening hours + address"], annotations:[{team:"design",text:"This is the page where the 'strictly offline' positioning must come through strongest."},{team:"dev",text:"Google Maps embed with custom styling. Opening hours as structured data (Schema.org LocalBusiness)."}] },
      { type:"grid", title:"Brands", desc:"Denim brands and independent designers carried in-store.", content:["Denim brands: Benzak, Edwin, KOI, Kuyichi, Nudie, Naked and Famous","Independent designers: Jouez les Enfants, Florian Regtien, Peter Wertmann, Jan de Vries, Wallflower","6-meter Jeans Wall: pairs of jeans on display, brands explained","No brand logo grid — each brand deserves context and story"], annotations:[{team:"design",text:"No brand logo grid. Each brand deserves context."},{team:"dev",text:"CMS-driven content so brands can be easily added/removed."}] },
      { type:"section", title:"Collabs", desc:"Limited editions and collaborative products available in-store.", content:["Very GoodS Studio (candles)","Mood Denim (spray)","Royal Delft x Henk Schiffmacher","Rotating selection — highlight what's current"], annotations:[{team:"design",text:"Collabs should feel special and limited. Not a regular product listing."},{team:"dev",text:"CMS-driven so collabs can be swapped seasonally."}] },
      { type:"section", title:"Fabrics", desc:"Fabric Wall — fabric by the meter for makers and designers.", content:["Fabric Wall: raw selvedge to innovative stretch","Sold by the meter — for makers, designers, and studios","Sourcing: Japanese selvedge, Italian stretch, organic cotton, deadstock","Not a webshop-style listing. Mood images + short description."], annotations:[{team:"design",text:"Tactile, material-focused. Show texture, weight, weave."}] },
      { type:"section", title:"Repair & Customization", desc:"Services to extend and personalize denim.", content:["Repair: 'Free repair for life' partner for Nudie. Dedicated partner for KOI.","Customization: upgrades, patches, personalization","Hemming: genuine chain stitching","Walk-in or by appointment"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Repair B2B': For brand partnership inquiries. Webflow form → GHL pipeline with auto-tagging."},{team:"ghl",text:"GHL BOOKING: Repair/customization appointments via Calendly → GHL. Confirmation + reminder automated."},{team:"dev",text:"Own CTA with booking link."}] },
      { type:"section", title:"Made to Order", desc:"Tailor-made jeans crafted by Incubator talent.", content:["Bespoke jeans: choose fabric, fit, details","Made by Incubator talent on-site","Process: consultation → measurement → production → fitting","Turnaround and pricing TBD from Milene"], annotations:[{team:"design",text:"Premium feel. This is the top-tier service offering."},{team:"dev",text:"Separate intake form with measurement fields. Dedicated CTA."}] },
    ]},
    { id:"education", label:"Education", nav:true, parent:null, blocks:[
      { type:"hero", title:"Education", desc:"All learning programs under the Denim City and House of Denim umbrella.", content:["Three pillars: Academy (courses), Incubator (talent development), Jean School (degree programs)","Supporting resources: Archive and Library","One page for all audiences — pricing tiers handle the differentiation at the point of booking"], annotations:[{team:"design",text:"Education landing page — route visitors to the right program. Not a course catalog."},{team:"dev",text:"No audience routing. All courses visible to everyone. Pricing table per course differentiates."}] },
      { type:"grid", title:"Academy", desc:"Denim City Academy by House of Denim — courses for all audiences.", content:["Full list: Make Your Own Jeans ⭐, Jacket, Kimono, Bag, Customize/Upcycle, Sashiko, Repair, Denim 101, eDesigner","Summer/Winter School programs for student groups","Team building workshops and custom programs for companies","Each course shows a pricing table with tiers (see Pricing block below)"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Courses': Every booking → pipeline. Automations: confirmation, reminder, post-course feedback + upsell (30d)."},{team:"ghl",text:"GHL ABANDONED BOOKING: Recovery sequence at 1h, 24h, 72h."},{team:"dev",text:"Each course card shows pricing tiers inline. No audience filter needed."}] },
      { type:"section", title:"Pricing & Booking", desc:"Contextual pricing tiers per course — the audience differentiation happens here, not on a separate page.", content:["Consumer: standard rate (individual booking)","Student: reduced rate (valid student ID required)","Professional: professional rate (higher tier, includes extras like certificate, materials, extended access)","Group / School: institutional rate (min. 8 participants, custom scheduling, invoice billing)","Pricing shown per course at booking step — not hidden behind audience selection"], annotations:[{team:"design",text:"Clean pricing table per course. Not a separate pricing page. The tiers should feel inclusive, not gatekeeping."},{team:"dev",text:"Pricing tiers as structured data per course. GHL form pre-fills the tier based on selection."},{team:"ghl",text:"GHL FORM: Booking form includes tier selection. Tier determines pipeline tags and follow-up sequence (e.g. student gets school partnership upsell, professional gets lab services upsell)."}] },
      { type:"section", title:"Incubator", desc:"By House of Denim — a modern guild for denim talent.", content:["57 talents, ~8 daily on-site, 550+ worldwide, 95% progression","Guild model: Intern → Trial → Incubator","Roles: repair specialists, wash masters, made-to-order designers, teachers, retail, micro-entrepreneurs","For brands: hire Incubator talent for small productions, capsule collections, workshops, launches, trade shows","Application: CV, portfolio, motivation, trial day(s)"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Incubator': Application → review → trial day → acceptance. Longest pipeline."},{team:"design",text:"Numbers prominent but not as infographic. Integrate into the story."}] },
      { type:"section", title:"Jean School", desc:"We are cofounders. We wrote the curriculum. We are the location.", content:["3-year Dutch + 1-year International program","Only school: store in front, lab in back, school upstairs","Revenue: rent + curriculum licensing fee","Cross-sell: 'Don't want 3 or 1 year? Book a Denim City Academy course.'"], annotations:[{team:"dev",text:"Do NOT become their marketing department. Link to jeanschool.com. External link, opens in new tab."},{team:"design",text:"Single section, compact. Positions our role, not their offering."}] },
      { type:"section", title:"Archive", desc:"Denim City's physical denim archive — a research and inspiration resource.", content:["Historical denim pieces and reference garments","Available for research visits, brand consultations, and educational programs","By appointment"], annotations:[{team:"design",text:"Reverent, museum-like. Show the depth of the collection."}] },
      { type:"section", title:"Library", desc:"Curated denim and textile library on-site.", content:["Books, magazines, and reference materials on denim, textiles, and fashion","Open to visitors, students, and researchers","Complements the Archive and Academy programs"], annotations:[{team:"design",text:"Warm, inviting. Not a dusty shelf — a living resource."}] },
    ]},
    { id:"lab", label:"Lab & Atelier", nav:true, parent:null, blocks:[
      { type:"hero", title:"Lab & Atelier", desc:"'The only lab in the Netherlands.' Sustainable Laundry Lab + Atelier production.", content:["Positioning: 'Only lab in the Netherlands / Northern mainland Europe'","Visuals: the machines, the work, the wash results","Equipment: Laser (Jeanologia eDesigner), Ozone, EcoStone, Natural dyes, Coatings","Rigmic Partnership: washmaster Pauline, 'premier league' lab"], annotations:[{team:"design",text:"Industrial, but not 'factory'. Lab feel: clean, innovative, precision."},{team:"design",text:"Show equipment visually, not as a bullet list."}] },
      { type:"section", title:"Sustainable Laundry R&D", desc:"Research and development for sustainable wash and finish techniques.", content:["Ozone washing, EcoStone, natural dyes, low-water processes","Developing new sustainable alternatives for conventional finishing","Collaboration with brands and researchers on innovation projects","Testing and validation for new wash recipes"], annotations:[{team:"design",text:"Science meets craft. Show the R&D process, not just the results."},{team:"ghl",text:"GHL PIPELINE 'Lab/Atelier': R&D inquiries → intake form → project scoping."}] },
      { type:"section", title:"Prototype & Sample Development", desc:"From sketch to sample — rapid prototyping for brands and designers.", content:["Pattern making, first samples, fit iterations","Wash development and sample washings","Small-batch testing before committing to production","Team: Jos (master tailor), Jan de Vries, Incubator talent"], annotations:[{team:"dev",text:"Own CTA with intake form. Separate from production inquiries."},{team:"ghl",text:"GHL: Prototype inquiries → Lab/Atelier pipeline with 'prototype' tag."}] },
      { type:"section", title:"Capsule Collections", desc:"End-to-end capsule production up to ~100 pieces.", content:["From concept to finished collection","Fabric sourcing, pattern, production, wash & finish — all in-house","Ideal for independent labels and emerging designers","Industrial sewing machines + atelier capacity"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Lab/Atelier': Capsule inquiries → quote → project tracking."},{team:"design",text:"Show completed capsule projects as case studies."}] },
      { type:"section", title:"Made-to-Order", desc:"Bespoke garments for individuals and small orders.", content:["Tailor-made jeans, jackets, and custom pieces","Choose fabric, fit, details — made by Incubator talent on-site","Process: consultation → measurement → production → fitting"], annotations:[{team:"dev",text:"Separate intake form with measurement fields. Dedicated CTA."},{team:"design",text:"Premium, personal feel. This is the luxury tier."}] },
      { type:"section", title:"Custom Made Products", desc:"White-label and custom product development for brands and companies.", content:["Co-branded merchandise and custom denim products","Corporate gifts, event merchandise, branded workwear","From design to delivery — managed end-to-end","MOQ and pricing on inquiry"], annotations:[{team:"ghl",text:"GHL: Custom product inquiries → Lab/Atelier pipeline with 'custom' tag. B2B nurture sequence."},{team:"dev",text:"B2B inquiry form with project scope fields."}] },
      { type:"section", title:"Who Is This For?", desc:"Contextual CTAs — the audience differentiation happens here, within the service page.", content:["Individual maker or designer? → Made-to-Order intake form (personal project)","Brand or label? → Lab inquiry form (prototype, capsule, R&D project)","School or university? → Educational lab access form (student group, research visit)","Each CTA leads to the same Lab/Atelier pipeline in GHL, tagged by audience type"], annotations:[{team:"design",text:"Not a wall of text. Three clear cards or CTAs with distinct visual identity. The visitor self-selects by intent, not identity."},{team:"ghl",text:"GHL: All three CTAs feed into Lab/Atelier pipeline. Tag determines follow-up sequence: individual gets portfolio upsell, brand gets B2B nurture, school gets institutional partnership pitch."}] },
    ]},
    { id:"tours", label:"Tours", nav:true, parent:null, blocks:[
      { type:"hero", title:"Tour Hero", desc:"'If you ever did a tour, you will never buy the same way again.'", content:["One tour experience — pricing varies by who you are","Direct booking CTA"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Tours': Booking → confirmation → reminder → post-tour nurture + upsell."},{team:"ghl",text:"GHL TOUR→COURSE CONVERSION: Auto email sequence after tour."}] },
      { type:"section", title:"Tour Pricing", desc:"Contextual pricing — audience differentiation at the point of booking.", content:["Educational / Students: €250 (schools, universities, NGOs)","Commercial / Corporate: €500 (brands, companies, team outings)","Individual: €TBD (private visitors, small groups — pricing from Milene needed)","Group size and date selected at booking — pricing auto-applied based on type"], annotations:[{team:"dev",text:"Pricing shown clearly on page. Booking form asks 'type of visit' which determines rate."},{team:"ghl",text:"GHL: Tour type selection in form → correct pricing + pipeline tags. Educational tours get school partnership follow-up, commercial tours get B2B nurture."}] },
      { type:"section", title:"What You'll See", desc:"Tour content without giving it away.", content:["Sustainability is cool, not boring","Circularity is practical","Value of product","Four guides: Jos (archive), Mariette (sustainability), Bowie (lab/wash), Jan (craftsmanship)"], annotations:[{team:"design",text:"Give a taste, not the full tour. Mood images only."}] },
      { type:"cta", title:"Booking", desc:"Direct booking flow.", content:["Calendly embed or custom booking form","Choice: Educational / Commercial","Date + group size"], annotations:[{team:"ghl",text:"Calendly → GHL: Sync booking data as contact properties."},{team:"dev",text:"Calendly inline embed with Denim City styling. No redirect."}] },
    ]},
    { id:"collaborate", label:"Collaborate", nav:true, parent:null, blocks:[
      { type:"hero", title:"Collaborate Hero", desc:"Three forms of collaboration, each with its own logic.", content:["Collabs: commercial partnerships (Lycra, KOI, Denham)","Partnerships: structural, often in kind (Oficina, MIC, APXpress, Jeanalogia)","Non-profit funding: House of Denim Foundation"], annotations:[{team:"design",text:"Three tracks visually distinct. Not three identical columns."}] },
      { type:"section", title:"Projects Showcase", desc:"Existing projects as social proof.", content:["Categories: Industry / Cultural / Private","Examples: Team NL Olympics x Denham, Amsterdam Museum, FLAX project","NRI 3001 NOT to be shown (NDA)"], annotations:[{team:"dev",text:"CMS-driven. Each project as case study card. Filterable by category."}] },
      { type:"section", title:"Partnership Packages", desc:"Tiers for different types of partners.", content:["Community Partner: €1,000 — individual professionals, small studios, emerging labels","Industry Partner: €5,000+ — established brands, retailers, production companies","Strategic Partner: €15-20K — institutional partners, schools, foundations","Transparency: show the value chain per tier","Details from Milene needed"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Partnerships': Inquiry → discovery call → proposal. Long B2B nurture."},{team:"design",text:"Pricing tiers shown clearly. Not hidden behind a contact form. Transparency builds trust."}] },
      { type:"cta", title:"Funding / Support", desc:"Separate section for funders.", content:["PVH Foundation as reference (Commitment #9, D&I)","Sponsor deck: needs to be created","CTA: 'Talk to us about funding'"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Funding': Inquiry → application → reporting. Separate pipeline."}] },
    ]},
    { id:"about", label:"About / Story", nav:true, parent:null, blocks:[
      { type:"section", title:"Origin Story", desc:"Denim City timeline.", content:["2008: 'Something has to change. Why not Amsterdam?'","2010: First co-creation, House of Denim Foundation","2012: Jean School, NY Times","2014: Kingpins → Amsterdam","2015: Denim City in De Hallen","2022: Incubator Program","Future: São Paulo, Istanbul, Joburg"], annotations:[{team:"design",text:"Timeline not as vertical line with dots. Find a form that fits Denim City."}] },
      { type:"section", title:"Team", desc:"Who to feature.", content:["James Veenhof — Co-founder","Mariette Hoitink — Co-founder","Jos — Master tailor","The team"], annotations:[{team:"design",text:"Real portraits, in their element."}] },
      { type:"section", title:"House of Denim", desc:"The foundation behind Denim City.", content:["Non-profit foundation","Mission: 'Advocate the good, collaborate for the better, educate the best'","'Towards a Brighter Blue'","Cofounders of Jean School, creators of Denim City"], annotations:[] },
    ]},
    { id:"contact", label:"Contact", nav:true, parent:null, blocks:[
      { type:"section", title:"Contact Hub", desc:"One contact page, multiple entry points.", content:["Form with dropdown: what are you reaching out about?","Options: Store, Courses, Tours, Lab, Partnerships, Venue, Press, Incubator, Other","Based on choice: correct fields + correct GHL pipeline"], annotations:[{team:"ghl",text:"GHL SMART ROUTING: Form choice determines pipeline, tags, automation sequence. Webflow → GHL webhook."},{team:"ghl",text:"GHL PIPELINES: Tours, Courses, Lab/Atelier, Partnerships, Venue, Funding, Press, Incubator, Repair B2B."},{team:"dev",text:"Dynamic form: fields change on dropdown. Not 9 separate forms."}] },
    ]},
    { id:"venue", label:"Venue Rental", nav:false, parent:null, blocks:[
      { type:"hero", title:"Venue Rental", desc:"Landing page, not in main nav. 'Huge unmet demand.'", content:["Archive space: €2,000 base","Extras separate: cleaning, bar, catering, tech","Best model: collaboration with Hallen Studios"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Venue': Inquiry → availability → quote → contract. 48h follow-up."},{team:"dev",text:"Not in main nav. Footer + direct URL. SEO-optimize."}] },
    ]},
    { id:"press", label:"Press", nav:false, parent:null, blocks:[
      { type:"section", title:"Press Releases", desc:"Overview of all published press releases.", content:["Chronological list of press releases","Each release: title, date, summary, full text or PDF download","Filterable by year or topic"], annotations:[{team:"dev",text:"CMS-driven. Each press release as its own entry with date, title, and downloadable PDF."},{team:"design",text:"Clean, editorial layout. Date-stamped entries."}] },
      { type:"section", title:"Downloadable Imagery", desc:"Press-ready images and visual assets for media use.", content:["High-resolution photos: location, team, products, events","Logo pack: Denim City, House of Denim (various formats)","Brand guidelines and usage instructions","ZIP download per category or individual download"], annotations:[{team:"dev",text:"Hosted image gallery with download links. Consider ZIP bundles per category."},{team:"design",text:"Grid layout with preview thumbnails. Clear download buttons."}] },
      { type:"cta", title:"Press Inquiries", desc:"Contact point for media and press.", content:["Press inquiry form — name, outlet, topic, deadline","Direct email as fallback"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Press': Inquiry → follow-up. Simplest pipeline."}] },
    ]},
    { id:"saopaulo", label:"São Paulo", nav:false, parent:null, blocks:[
      { type:"section", title:"Denim City São Paulo", desc:"Separate section, not in main nav. Teaser on home.", content:["Location info, offerings, connection to Amsterdam","Brand guidelines with floor stickers"], annotations:[{team:"dev",text:"Not in main nav. Home teaser + footer."}] },
    ]},
  ];
}

export const GHL_PIPES: GhlPipeline[] = [
  { n: "Tours", t: "Booking/Calendly", a: "Confirmation, reminder, post-tour nurture, tour→course conversion" },
  { n: "Courses", t: "Booking/Calendly", a: "Confirmation, reminder, feedback, upsell (30d), abandoned recovery, certificate" },
  { n: "Lab/Atelier", t: "Inquiry form (3 tracks)", a: "Inquiry → quote → project tracking. Sub-flows per audience." },
  { n: "Partnerships", t: "Inquiry form", a: "Inquiry → discovery → proposal. Long B2B nurture." },
  { n: "Venue", t: "Inquiry form", a: "Inquiry → availability → quote → contract. 48h follow-up." },
  { n: "Funding", t: "Inquiry form", a: "Inquiry → application → reporting." },
  { n: "Press", t: "Inquiry form", a: "Inquiry → follow-up." },
  { n: "Incubator", t: "Application form", a: "Intake → review → trial day → acceptance." },
  { n: "Repair B2B", t: "Partnership inquiry", a: "Brand inquiry → discovery → onboarding." },
];

export const GHL_INT: GhlIntegration[] = [
  { s: "Lightspeed R", d: "→ GHL", p: "Store purchases → customer data + post-purchase nurture" },
  { s: "Webflow", d: "→ GHL", p: "All forms. Webhooks per form to correct pipeline." },
  { s: "Calendly", d: "→ GHL", p: "All bookings. Sync to GHL contacts + pipeline." },
];

export const UNIVERSAL_AUTOMATIONS = [
  "Booking confirmations + reminders (24h)",
  "Post-experience feedback",
  "Abandoned booking recovery (1h, 24h, 72h)",
  "Cross-sell sequences per service",
  "Certificate delivery (courses)",
  "Audience segmentation via pricing tier / form selection (consumer, student, professional, institutional)",
];
