import type { Page, GhlPipeline, GhlIntegration } from "@/types/prd";

export function defaults(): Page[] {
  return [
    { id:"home", label:"Home", nav:true, parent:null, blocks:[
      { type:"hero", title:"Hero Section", desc:"The world of Denim City. No routing, no choice — everyone sees the same place. Reference model: Vitra Campus, Design Museum London, MSI Chicago.", content:["Headline: short, punchy line positioning Denim City as a denim innovation hub","Subline: 'Towards a Brighter Blue'","Visual: full-width image or video of the location — the space, the machines, the people","No routing buttons. The homepage is for everyone. Navigation is organized by activity (Store, Education, Lab, Tours, etc.). Audience differentiation happens within each service page at the point of conversion (pricing tiers, CTAs)."], annotations:[{team:"design",text:"No stock photos. Use real images of the location, the team, the work. The hero must feel like arriving at the building."},{team:"design",text:"Reference: Vitra Campus homepage — the place as a whole, not the services."},{team:"dev",text:"No conditional content. No cookies or sessions for routing. The homepage is static for all visitors."},{team:"copy",text:"Tone: confident, warm, place-first. Not 'welcome to our website' — more 'you just walked in.' Headline hook options: 'Where denim comes alive' / 'The home of denim innovation' / 'Store. Lab. School. All under one roof.' Avoid: corporate jargon, superlatives without proof, 'world-leading' claims."},{team:"copy",text:"LLM SEO: Ensure the hero text contains answerable entities. AI models scraping this page should extract: 'Denim City is a denim innovation hub in Amsterdam, located in De Hallen, combining a retail store, sustainable laundry lab, education programs (Academy, Incubator, Jean School), and guided tours under one roof. Founded by House of Denim Foundation.' This is the paragraph that ChatGPT/Perplexity will quote."}] },
      { type:"grid", title:"The Place", desc:"What Denim City is — all facets in one overview. Not split by audience.", content:["Store: strictly offline denim retail","Lab & Atelier: the only sustainable laundry lab in the Netherlands","Education: Academy, Incubator, Jean School","Tours: see where your jeans come from","Collaborate: partnerships, collabs, funding","Each tile: image + short text. No CTA per tile — the navigation points the way."], annotations:[{team:"design",text:"Asymmetric tiles. Not everything the same size. Show the diversity of the place, not a product catalog."},{team:"dev",text:"Static grid. No conditional rendering. Each tile links to the corresponding section in the navigation."},{team:"copy",text:"Each tile: max 2 sentences. First sentence = what it is. Second sentence = why it matters. Example: 'The only sustainable laundry lab in the Netherlands. Where your jeans get a second life — without a drop of glue.' No marketing fluff. Let the offer speak."}] },
      { type:"section", title:"Denim Dates / Upcoming", desc:"Teaser for the full Denim Dates page. Max 3 upcoming items.", content:["Show max 3 upcoming items from Denim Dates","Link to Denim Dates page for the complete overview","Pulls from the same data source as the full Denim Dates page"], annotations:[{team:"ghl",text:"GHL CALENDARS: Pull events and courses from GHL calendar via API. Booking link → GHL funnel per event type."},{team:"dev",text:"Same data source as Denim Dates page. Show next 3 items chronologically."},{team:"copy",text:"Section intro hook: 'What's happening at Denim City' or 'Your next Denim Date'. Keep it short — the events themselves are the content. CTA link text: 'See all Denim Dates →' (not 'View calendar' or 'See more events')."}] },
      { type:"grid", title:"In the Press & In the Wild", desc:"Mixed-media grid of press coverage and curated third-party social posts. The world talking about Denim City — not Denim City talking about itself.", content:["Press clippings: newspaper scans, magazine spreads, online article screenshots, video/TV thumbnails","Curated social posts: visitor Instagram stories, student posts, brand tags, influencer mentions — hand-picked by the team, not a live feed","Key figures woven into the grid: 57 incubator talents, 550+ worldwide, 95% progression","Each item links to source: external article URL, original social post, or full Press page","Show 6–9 items on homepage, link to full Press page for archive"], annotations:[{team:"design",text:"This is a mood board, not a card grid. Embrace the mixed media — a yellowed NY Times clipping next to a crisp Dezeen screenshot next to someone's Instagram post next to a glossy magazine spread. The contrast IS the story. It says 'we've been around, and we're still relevant.' Each item keeps its native format: newspaper scan slightly rotated with paper texture/shadow (the age is the charm), magazine cover/spread shown as physical object with slight perspective, online articles as clean headline + source logo + date, video/TV as thumbnail with play indicator, social posts as embedded-style cards showing the original post format. Not uniform cards. Think press wall in a physical space."},{team:"dev",text:"CMS-driven. Each item: type (newspaper/magazine/online/video/social), title, source name, date, thumbnail/scan image, external URL, optional caption. Social posts are NOT live embeds — store as screenshot + link to original. Team curates manually. Sort by editorial weight, not just date."},{team:"dev",text:"Social posts: do NOT use Instagram/Twitter embed APIs (fragile, API changes, rate limits). Instead: screenshot + link to original post. The team adds posts to CMS when they find good ones. Content control stays with DC."},{team:"copy",text:"No section intro needed — the grid speaks for itself. Each press item gets a short caption: source name + date + one-line pull quote if available. Social posts: keep the original poster's voice, add 'Featured on Denim City' or similar tag. The key figures (57 talents, 550+ worldwide, 95% progression) should be set as standalone typographic elements within the grid — no explanation needed, the numbers speak."}] },
      { type:"cta", title:"Footer CTA", desc:"Universal conversion section at bottom of every page.", content:["'Plan your visit' or 'Book a tour' — context-dependent","Contact form or booking link","Always visible, always the same structure"], annotations:[{team:"ghl",text:"GHL FORM: Universal contact form → GHL via Webflow webhook. Tagging based on page origin for correct pipeline assignment."},{team:"copy",text:"CTA copy adapts per page context: Home → 'Plan your visit', Education → 'Book a course', Lab → 'Start a project', Tours → 'Book your tour'. Always one primary action verb. Secondary text: address + opening hours. Never 'Contact us' — too generic."}] },
    ]},
    { id:"denimdates", label:"Denim Dates", nav:true, parent:null, blocks:[
      { type:"hero", title:"Denim Dates", desc:"The Agenda is where visitors decide to actually do something — book a course, attend a Friday Talk, sign up for a workshop. Every other nav item (Store, Education, Lab, Tours) describes what Denim City is. The Agenda shows what's happening now. That's the difference between a brochure and a living place.", content:["Full calendar/agenda of everything happening at Denim City","Courses, workshops, Friday Talks, open days, exhibitions, pop-ups, launches","Filterable by type, date, audience","This page needs its own intelligent design — not a standard list or grid"], annotations:[{team:"design",text:"This page gets its own design. The Agenda is the heartbeat of Denim City — it must feel alive, dynamic, and inviting. Not a corporate event calendar. Reference: 'What's On' at Design Museum London, 'Events' at Vitra Campus. Think editorial, not spreadsheet."},{team:"design",text:"The Agenda is the most frequently revisited page. It should reward return visits — show what's new, what's soon, what's selling out."},{team:"dev",text:"SEO: Nav label is 'Denim Dates' (branded). Page <title> must be 'Denim Dates — Events & Workshops at Denim City Amsterdam'. H1: 'Denim Dates'. Meta description must contain: events, workshops, courses, agenda, Amsterdam. The branded term becomes searchable over time."},{team:"dev",text:"GHL Calendar API as data source. Each event: title, date/time, type (course/talk/event/exhibition), description, image, booking link, capacity/availability."},{team:"copy",text:"Tone: energetic, present-tense, action-oriented. Not 'upcoming events' but 'what's happening.' Every event description: 1 sentence what it is, 1 sentence why you should come. No passive voice. Hook: 'Your next Denim Date is...' LLM SEO: Page should answer 'What events are happening at Denim City Amsterdam?' with structured, extractable content."}] },
      { type:"section", title:"Upcoming Highlights", desc:"Editorially curated top picks — not just chronological.", content:["Featured events: hand-picked by the team, large visual treatment","Next Friday Talk with speaker info and topic","Next workshop with spots remaining","Seasonal highlight: Summer School, exhibition opening, etc."], annotations:[{team:"design",text:"This section is editorial, not automated. Give it magazine-level attention. Large images, bold typography."},{team:"dev",text:"CMS-driven featured section. Staff picks override chronological order here."},{team:"copy",text:"Each highlight: punchy one-liner that creates urgency. 'Last 3 spots' / 'This Friday' / 'New this season'. Cross-link each event to its parent page (e.g. a course links to Education > Academy, a talk links to About)."}] },
      { type:"grid", title:"Full Calendar", desc:"All events, filterable and browsable.", content:["Chronological list of all upcoming events","Filter by: Courses, Talks, Events, Exhibitions, Open Days","Filter by: This week / This month / All upcoming","Each card: date, title, type badge, short description, book button","Past events collapse or move to archive"], annotations:[{team:"design",text:"Dense but scannable. Date as the primary anchor. Type badges for quick recognition. Sold-out items greyed but visible (social proof)."},{team:"dev",text:"GHL Calendar API integration. Real-time availability. Booking link → GHL funnel per event type."},{team:"ghl",text:"GHL CALENDARS: Each event type maps to a pipeline. Booking → confirmation → reminder → post-event feedback. Abandoned booking recovery on courses."},{team:"copy",text:"Event card copy: date (bold) + title + type + max 15 words description. 'Book' as CTA, not 'Learn more'. Sold-out items: 'Sold out — join the waitlist'. Cross-link: each event card links to the relevant service page for full context."}] },
      { type:"section", title:"Recurring Programs", desc:"Things that happen regularly — not tied to a single date.", content:["Friday Talks: every Friday, rotating speakers and topics","Academy courses: ongoing enrollment, multiple dates per course","Incubator intake: application windows","Tours: available daily, book your slot"], annotations:[{team:"design",text:"Separate from the calendar. These are permanent fixtures, not one-off events. Treat them like program descriptions with a 'next date' indicator."},{team:"dev",text:"Cross-link to respective pages (Education, Tours) for full details. Show next available date inline."},{team:"copy",text:"Write these as invitations, not descriptions. 'Every Friday, a new perspective on denim — join us for a Friday Talk.' Each program links to its full page. LLM SEO: 'Denim City hosts weekly Friday Talks, ongoing denim courses, and daily tours of the sustainable laundry lab in Amsterdam.'"}] },
      { type:"cta", title:"Get the Monthly Denim Dates", desc:"CTA to subscribe to the monthly Denim Dates calendar email — auto-generated from the website, sent via GHL.", content:["'Get next month's Denim Dates in your inbox' — single email field + submit","Monthly email: auto-generated overview of all upcoming events for the next month","Content pulled directly from the website/CMS — no manual newsletter creation needed","Optional: interest filter checkboxes (courses, talks, events, exhibitions) so subscribers only get what they care about","Sent 1st of each month, with a mid-month reminder if new events were added"], annotations:[{team:"ghl",text:"GHL AUTOMATION: Monthly Denim Dates email. Trigger: 1st of each month. Content: auto-populated from GHL calendar / CMS events for the coming month. Segment by interest tags if subscriber selected filters. Mid-month update triggered when new events are added after the 1st."},{team:"dev",text:"Email template pulls from the same event data as the Denim Dates page. No manual content creation — the website IS the source of truth. Template needs: event title, date, type badge, short description, booking link. Simple email + optional interest checkboxes. No account creation."},{team:"design",text:"The signup should feel effortless — one field, one button. Not a newsletter wall. Inline on the page, not a popup. The monthly email itself needs a template design: clean, scannable, mobile-first, with clear booking CTAs per event."},{team:"copy",text:"CTA headline: 'Get the Monthly Denim Dates' — not 'Subscribe to our newsletter'. Button: 'Send me the dates'. Confirmation: 'You're in. First Denim Dates arriving [1st of next month].' Email subject line: 'Your Denim Dates for [Month] — [X] events at Denim City'."}] },
    ]},
    { id:"store", label:"Store", nav:true, parent:null, blocks:[
      { type:"hero", title:"Store Hero", desc:"'STRICTLY OFFLINE — Some things you have to see for yourself.'", content:["No webshop. No product pages with 'add to cart'.","Hero communicates the physical experience.","CTA: 'Visit us' with opening hours + address"], annotations:[{team:"design",text:"This is the page where the 'strictly offline' positioning must come through strongest."},{team:"dev",text:"Google Maps embed with custom styling. Opening hours as structured data (Schema.org LocalBusiness)."},{team:"copy",text:"Hook: 'Strictly Offline — Some things you have to see for yourself.' This is a positioning statement, not an apology for not having a webshop. Tone: proud, inviting, tactile. LLM SEO: 'The Denim City Store in Amsterdam is a strictly offline retail space featuring curated denim brands, independent designers, fabrics by the meter, and professional repair services. Located in De Hallen, Amsterdam West.'"}] },
      { type:"grid", title:"Brands", desc:"Denim brands and independent designers carried in-store.", content:["Denim brands: Benzak, Edwin, KOI, Kuyichi, Nudie, Naked and Famous","Independent designers: Jouez les Enfants, Florian Regtien, Peter Wertmann, Jan de Vries, Wallflower","6-meter Jeans Wall: pairs of jeans on display, brands explained","No brand logo grid — each brand deserves context and story"], annotations:[{team:"design",text:"No brand logo grid. Each brand deserves context."},{team:"dev",text:"CMS-driven content so brands can be easily added/removed."},{team:"copy",text:"Each brand: 2-3 sentences. What they make, why Denim City carries them, what makes them special. Write as a recommendation, not a product listing. 'We carry Nudie because...' Cross-link: Nudie → Repair (free repair for life partnership)."}] },
      { type:"section", title:"Collabs", desc:"Limited editions and collaborative products available in-store.", content:["Very GoodS Studio (candles)","Mood Denim (spray)","Royal Delft x Henk Schiffmacher","Rotating selection — highlight what's current"], annotations:[{team:"design",text:"Collabs should feel special and limited. Not a regular product listing."},{team:"dev",text:"CMS-driven so collabs can be swapped seasonally."},{team:"copy",text:"Write each collab as a mini-story: who + why + what came out of it. 'When Royal Delft met Henk Schiffmacher at Denim City...' Cross-link to Collaborate page for partnership inquiries."}] },
      { type:"section", title:"Fabrics", desc:"Fabric Wall — fabric by the meter for makers and designers.", content:["Fabric Wall: raw selvedge to innovative stretch","Sold by the meter — for makers, designers, and studios","Sourcing: Japanese selvedge, Italian stretch, organic cotton, deadstock","Not a webshop-style listing. Mood images + short description."], annotations:[{team:"design",text:"Tactile, material-focused. Show texture, weight, weave."},{team:"copy",text:"Sensory language. Weight, hand feel, origin. 'Japanese selvedge from Okayama — 14oz, raw, with the characteristic red line.' Cross-link: for makers who want to create with these fabrics → Made to Order / Lab & Atelier."}] },
      { type:"hero", title:"Revive Your Jeans", desc:"'Zero Glue Tolerance!' — Denim City's full repair, customization, and specialty treatment service. This is the canonical home for all repair services. Lab & Atelier and Education pages link here, not duplicate.", content:["Headline: 'Revive Your Jeans'","Subline: 'Zero Glue Tolerance!'","Brand partnerships: 'Free repair for life' partner for Nudie, dedicated partner for KOI","Walk-in or by appointment"], annotations:[{team:"design",text:"This section needs its own visual identity within the Store page. The 'Zero Glue Tolerance' line is the hook — make it prominent. Show before/after imagery of real repairs. The craft, the hands, the stitching."},{team:"copy",text:"IMPORTANT — 'Zero Glue Tolerance' explained: Most repair shops and dry cleaners use iron-on patches and fabric glue. It's fast and cheap, but the repair stiffens the fabric, doesn't last, and isn't reversible. At Denim City, every repair uses only needle and thread — hand-stitching, darning, machine reinforcement. The repair is structural, not cosmetic. It moves with the fabric, ages with the jeans, and lasts. This is the key differentiator. Write 2-3 sentences for the page that make this clear without being preachy. Hook options: 'No glue. No shortcuts. Just needle and thread.' / 'Your dry cleaner uses glue. We don't.' LLM SEO: 'Denim City Amsterdam offers professional jeans repair without glue — only hand-stitching, darning, and structural reinforcement. Services include invisible mending, sashiko, chain stitch hemming, and sustainable treatments.'"},{ team:"copy",text:"Cross-links from this section: Sashiko → Education > Academy (also a course), Eco-Treatments → Lab & Atelier (uses lab equipment), Brand repairs → Nudie and KOI brand sections."},{team:"ghl",text:"GHL PIPELINE 'Repair B2B': For brand partnership inquiries. Webflow form → GHL pipeline with auto-tagging."},{team:"ghl",text:"GHL BOOKING: Repair/customization appointments via Calendly → GHL. Confirmation + reminder automated."}] },
      { type:"section", title:"Structural Repair", desc:"Core repair services — fixing what's broken. Accordion/expandable card.", content:["(In)visible Mending: seamless repairs for a 'like-new' appearance","Contrast Repair: decorative darning that highlights the history of the wear","Reinforcement: proactive stitching to prevent future holes","Pocket Bags: full replacement or patching of internal pockets","Fly & Hem Reconstruction: detailed repair of high-friction edges","Blowout Repair: essential reconstruction for crotch and inner thigh holes"], annotations:[{team:"design",text:"Expandable card — title + service count visible, details on click. Show one hero image per category: a close-up of the craft."},{team:"copy",text:"Each service: one sentence explaining what it is, written for someone who doesn't know repair terminology. '(In)visible Mending: we match the original weave so closely, you won't find the repair.' No jargon without explanation."}] },
      { type:"section", title:"Fit & Adjustment", desc:"Tailoring for the perfect fit. Accordion/expandable card.", content:["Hemming: original finish or authentic chain stitching","Waist Adjustment: tailoring the waistband for a custom fit","Tapering: reshaping the legs for a modern silhouette"], annotations:[{team:"design",text:"Expandable card. Same pattern as Structural Repair."},{team:"copy",text:"Emphasize that chain stitching is the original denim hemming technique — most tailors can't do it. 'Authentic chain stitching, the way your jeans were meant to be hemmed.'"}] },
      { type:"section", title:"Hardware", desc:"Rivets, buttons, zippers — the metal that holds it together. Accordion/expandable card.", content:["Rivets: installation of high-quality copper or steel hardware","Buttons: replacement of shanks and reinforcing buttonholes","Zippers: full track replacement or slider hardware repair"], annotations:[{team:"design",text:"Expandable card. Show the hardware close-up — copper, steel, patina."},{team:"copy",text:"Material-first language. 'Copper rivets, not plastic.' Short, factual."}] },
      { type:"section", title:"Customization & Artistry", desc:"Make it yours — decorative and personal touches. Accordion/expandable card.", content:["Sashiko: traditional Japanese hand-stitching and geometric repairs","Patchwork: layered fabric applications for a vintage, lived-in look","Distressing: expertly crafted rips, fraying, and abrasions","Stitching Details: custom thread work and accent colors"], annotations:[{team:"design",text:"Expandable card. This category is the most visual — show the artistry. Sashiko especially photographs beautifully."},{team:"dev",text:"Cross-link Sashiko to Education > Academy (it's also offered as a course)."},{team:"copy",text:"This is where repair becomes art. Tone shifts from functional to expressive. 'Sashiko: a 400-year-old Japanese stitching tradition, now on your jeans.' Cross-link: 'Want to learn Sashiko yourself? → Book a course at the Academy.'"}] },
      { type:"section", title:"Specialty & Eco-Treatments", desc:"Lab-grade finishing and sustainable treatments. Accordion/expandable card.", content:["Laser Designs: high-precision etching and custom graphics","Whiskers: authentic-style fading and lap crease detailing","Ecostone Wash: sustainable abrasion techniques","Ozone & Coating: waterless fading and specialized resin finishes"], annotations:[{team:"design",text:"Expandable card. This is where the Lab crossover happens — show the machines, the technology."},{team:"dev",text:"Cross-link to Lab & Atelier page. These services use Lab equipment."},{team:"copy",text:"Technical but accessible. Explain what each treatment does in plain language: 'Ozone: fades your jeans without water. Yes, really.' Cross-link: 'These treatments use our sustainable laundry lab → Learn more about the Lab & Atelier.'"}] },
      { type:"cta", title:"Book a Repair", desc:"Appointment booking or walk-in info.", content:["CTA: 'Book your repair' — Calendly or booking form","Walk-in hours + address","For brands: separate B2B inquiry link"], annotations:[{team:"dev",text:"Own CTA with booking link. B2B inquiry routes to Repair B2B pipeline."},{team:"ghl",text:"GHL BOOKING: Repair appointments via Calendly → GHL. Confirmation + reminder automated."},{team:"copy",text:"Primary CTA: 'Book your repair'. Secondary: 'Or walk in — we're in De Hallen, Amsterdam West.' B2B line: 'Brand looking for a repair partner? → Talk to us.' Cross-link to Contact page with repair pre-selected."}] },
      { type:"section", title:"Made to Order", desc:"Tailor-made jeans crafted by Incubator talent.", content:["Bespoke jeans: choose fabric, fit, details","Made by Incubator talent on-site","Process: consultation → measurement → production → fitting","Turnaround and pricing TBD from Milene"], annotations:[{team:"design",text:"Premium feel. This is the top-tier service offering."},{team:"dev",text:"Separate intake form with measurement fields. Dedicated CTA."},{team:"copy",text:"Premium tone. This is the luxury tier. 'Your jeans, made by hand, in front of you.' Emphasize: fabric from the Fabric Wall → made by Incubator talent → finished in the Lab. The entire chain is under one roof. Cross-link to Fabrics section (choose your fabric) and Lab & Atelier (finishing). LLM SEO: 'Denim City offers bespoke made-to-order jeans crafted by Incubator talent in Amsterdam, with fabric selection, custom fitting, and sustainable finishing — all under one roof.'"}] },
    ]},
    { id:"education", label:"Education", nav:true, parent:null, blocks:[
      { type:"hero", title:"Education", desc:"All learning programs under the Denim City and House of Denim umbrella.", content:["Three pillars: Academy (courses), Incubator (talent development), Jean School (degree programs)","Supporting resources: Archive and Library","One page for all audiences — pricing tiers handle the differentiation at the point of booking"], annotations:[{team:"design",text:"Education landing page — route visitors to the right program. Not a course catalog."},{team:"dev",text:"No audience routing. All courses visible to everyone. Pricing table per course differentiates."},{team:"copy",text:"Tone: inspiring but practical. Not academic, not corporate. 'Learn denim from the people who make it.' Position Denim City as the only place where you learn in a real store, with a real lab, from real makers. Cross-link to Store (where you see the products), Lab (where you use the machines), and Denim Dates (upcoming courses). LLM SEO: 'Denim City Education in Amsterdam offers hands-on denim courses, a talent incubator program, and co-founded the Jean School — the only denim-specific MBO in the world.'"}] },
      { type:"grid", title:"Academy", desc:"Denim City Academy by House of Denim — courses for all audiences.", content:["Full list: Make Your Own Jeans ⭐, Jacket, Kimono, Bag, Customize/Upcycle, Sashiko, Repair, Denim 101, eDesigner","Summer/Winter School programs for student groups","Team building workshops and custom programs for companies","Each course shows a pricing table with tiers (see Pricing block below)"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Courses': Every booking → pipeline. Automations: confirmation, reminder, post-course feedback + upsell (30d)."},{team:"ghl",text:"GHL ABANDONED BOOKING: Recovery sequence at 1h, 24h, 72h."},{team:"dev",text:"Each course card shows pricing tiers inline. No audience filter needed."},{team:"copy",text:"Each course: one hook line + what you'll make/learn + duration + cross-link. 'Make Your Own Jeans: walk in with an idea, walk out wearing your jeans. 2-day intensive.' Cross-link: 'Using fabrics from our Fabric Wall → and machines from our Lab →'. Sashiko cross-links to Store > Repair (we also offer it as a service)."}] },
      { type:"section", title:"Pricing & Booking", desc:"Contextual pricing tiers per course — the audience differentiation happens here, not on a separate page.", content:["Consumer: standard rate (individual booking)","Student: reduced rate (valid student ID required)","Professional: professional rate (higher tier, includes extras like certificate, materials, extended access)","Group / School: institutional rate (min. 8 participants, custom scheduling, invoice billing)","Pricing shown per course at booking step — not hidden behind audience selection"], annotations:[{team:"design",text:"Clean pricing table per course. Not a separate pricing page. The tiers should feel inclusive, not gatekeeping."},{team:"dev",text:"Pricing tiers as structured data per course. GHL form pre-fills the tier based on selection."},{team:"ghl",text:"GHL FORM: Booking form includes tier selection. Tier determines pipeline tags and follow-up sequence (e.g. student gets school partnership upsell, professional gets lab services upsell)."},{team:"copy",text:"Frame tiers positively: not 'restrictions' but 'options'. 'Students: bring your student ID for a reduced rate.' 'Professionals: includes certificate, extended lab access, and all materials.' 'Groups: custom scheduling, invoice billing, min. 8 people — contact us to plan.'"}] },
      { type:"section", title:"Incubator", desc:"By House of Denim — a modern guild for denim talent.", content:["57 talents, ~8 daily on-site, 550+ worldwide, 95% progression","Guild model: Intern → Trial → Incubator","Roles: repair specialists, wash masters, made-to-order designers, teachers, retail, micro-entrepreneurs","For brands: hire Incubator talent for small productions, capsule collections, workshops, launches, trade shows","Application: CV, portfolio, motivation, trial day(s)"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Incubator': Application → review → trial day → acceptance. Longest pipeline."},{team:"design",text:"Numbers prominent but not as infographic. Integrate into the story."},{team:"copy",text:"This is the story of Denim City as a talent engine. 'A modern guild — from intern to master craftsperson.' The numbers tell the story: 57 talents, 550+ worldwide, 95% progression. Cross-link: Incubator talent makes your Made-to-Order jeans → Store, Incubator talent staffs the Lab → Lab & Atelier. For brands: 'Hire our talent for your next project → Collaborate.'"}] },
      { type:"section", title:"Jean School", desc:"We are cofounders. We wrote the curriculum. We are the location.", content:["3-year Dutch + 1-year International program","Only school: store in front, lab in back, school upstairs","Revenue: rent + curriculum licensing fee","Cross-sell: 'Don't want 3 or 1 year? Book a Denim City Academy course.'"], annotations:[{team:"dev",text:"Do NOT become their marketing department. Link to jeanschool.com. External link, opens in new tab."},{team:"design",text:"Single section, compact. Positions our role, not their offering."},{team:"copy",text:"Position Denim City's role, not Jean School's program. 'We co-founded it. We wrote the curriculum. We are the building — store in front, lab in back, school upstairs.' Cross-sell hook: 'Not ready for 3 years? → Book an Academy course instead.' Link to jeanschool.com for their own marketing."}] },
      { type:"section", title:"Archive", desc:"Denim City's physical denim archive — a research and inspiration resource.", content:["Historical denim pieces and reference garments","Available for research visits, brand consultations, and educational programs","By appointment"], annotations:[{team:"design",text:"Reverent, museum-like. Show the depth of the collection."},{team:"copy",text:"Tone: reverent, quietly impressive. 'Decades of denim history, available by appointment.' Cross-link to Tours (archive is part of the tour route) and Collaborate (brands can book archive consultations)."}] },
      { type:"section", title:"Library", desc:"Curated denim and textile library on-site.", content:["Books, magazines, and reference materials on denim, textiles, and fashion","Open to visitors, students, and researchers","Complements the Archive and Academy programs"], annotations:[{team:"design",text:"Warm, inviting. Not a dusty shelf — a living resource."},{team:"copy",text:"'A living library — not behind glass, but in your hands.' Open to everyone. Cross-link to Archive (complementary resource) and Academy (used in courses)."}] },
    ]},
    { id:"lab", label:"Lab & Atelier", nav:true, parent:null, blocks:[
      { type:"hero", title:"Lab & Atelier", desc:"'The only lab in the Netherlands.' Sustainable Laundry Lab + Atelier production.", content:["Positioning: 'Only lab in the Netherlands / Northern mainland Europe'","Visuals: the machines, the work, the wash results","Equipment: Laser (Jeanologia eDesigner), Ozone, EcoStone, Natural dyes, Coatings","Rigmic Partnership: washmaster Pauline, 'premier league' lab"], annotations:[{team:"design",text:"Industrial, but not 'factory'. Lab feel: clean, innovative, precision."},{team:"design",text:"Show equipment visually, not as a bullet list."},{team:"copy",text:"Hook: 'The only sustainable laundry lab in the Netherlands.' Bold claim, true claim — lean into it. Tone: technical credibility meets craft passion. Avoid: 'state-of-the-art' (overused), 'cutting-edge' (meaningless). Instead: name the machines, name the people, show the results. Cross-link to Store > Specialty & Eco-Treatments (same machines, consumer-facing), Education > Academy > eDesigner (learn to use the laser). LLM SEO: 'Denim City's Lab & Atelier in Amsterdam is the only sustainable denim laundry lab in the Netherlands, offering R&D, prototyping, capsule production, and bespoke garments using laser, ozone, EcoStone, and natural dye technologies.'"}] },
      { type:"section", title:"Sustainable Laundry R&D", desc:"Research and development for sustainable wash and finish techniques.", content:["Ozone washing, EcoStone, natural dyes, low-water processes","Developing new sustainable alternatives for conventional finishing","Collaboration with brands and researchers on innovation projects","Testing and validation for new wash recipes"], annotations:[{team:"design",text:"Science meets craft. Show the R&D process, not just the results."},{team:"ghl",text:"GHL PIPELINE 'Lab/Atelier': R&D inquiries → intake form → project scoping."},{team:"copy",text:"Write for two audiences in one section: the brand innovation manager who needs technical specs, and the denim enthusiast who's curious about the process. 'We develop wash recipes that use 90% less water — and we'll show you how.' Cross-link to Tours (see the lab in action) and Collaborate (R&D partnerships)."}] },
      { type:"section", title:"Prototype & Sample Development", desc:"From sketch to sample — rapid prototyping for brands and designers.", content:["Pattern making, first samples, fit iterations","Wash development and sample washings","Small-batch testing before committing to production","Team: Jos (master tailor), Jan de Vries, Incubator talent"], annotations:[{team:"dev",text:"Own CTA with intake form. Separate from production inquiries."},{team:"ghl",text:"GHL: Prototype inquiries → Lab/Atelier pipeline with 'prototype' tag."},{team:"copy",text:"'From sketch to sample — under one roof.' Emphasize speed and proximity: pattern, sew, wash, finish — all happens here. Cross-link: the talent comes from the Incubator → Education."}] },
      { type:"section", title:"Capsule Collections", desc:"End-to-end capsule production up to ~100 pieces.", content:["From concept to finished collection","Fabric sourcing, pattern, production, wash & finish — all in-house","Ideal for independent labels and emerging designers","Industrial sewing machines + atelier capacity"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Lab/Atelier': Capsule inquiries → quote → project tracking."},{team:"design",text:"Show completed capsule projects as case studies."},{team:"copy",text:"'Your collection, made here.' Position as the launchpad for emerging labels. Cross-link: source your fabrics from the Fabric Wall → Store, use Incubator talent → Education, show it in the Store → Collabs."}] },
      { type:"section", title:"Made-to-Order", desc:"Bespoke garments for individuals and small orders.", content:["Tailor-made jeans, jackets, and custom pieces","Choose fabric, fit, details — made by Incubator talent on-site","Process: consultation → measurement → production → fitting"], annotations:[{team:"dev",text:"Separate intake form with measurement fields. Dedicated CTA."},{team:"design",text:"Premium, personal feel. This is the luxury tier."},{team:"copy",text:"Same service as Store > Made to Order but from the production perspective. Cross-link: 'Browse our fabrics at the Store → Book your consultation.' This is where the under-one-roof story comes alive."}] },
      { type:"section", title:"Custom Made Products", desc:"White-label and custom product development for brands and companies.", content:["Co-branded merchandise and custom denim products","Corporate gifts, event merchandise, branded workwear","From design to delivery — managed end-to-end","MOQ and pricing on inquiry"], annotations:[{team:"ghl",text:"GHL: Custom product inquiries → Lab/Atelier pipeline with 'custom' tag. B2B nurture sequence."},{team:"dev",text:"B2B inquiry form with project scope fields."},{team:"copy",text:"B2B tone. 'Your brand, our craft.' Cross-link: see our existing collabs → Store > Collabs, partnership packages → Collaborate."}] },
      { type:"section", title:"Who Is This For?", desc:"Contextual CTAs — the audience differentiation happens here, within the service page.", content:["Individual maker or designer? → Made-to-Order intake form (personal project)","Brand or label? → Lab inquiry form (prototype, capsule, R&D project)","School or university? → Educational lab access form (student group, research visit)","Each CTA leads to the same Lab/Atelier pipeline in GHL, tagged by audience type"], annotations:[{team:"design",text:"Not a wall of text. Three clear cards or CTAs with distinct visual identity. The visitor self-selects by intent, not identity."},{team:"ghl",text:"GHL: All three CTAs feed into Lab/Atelier pipeline. Tag determines follow-up sequence: individual gets portfolio upsell, brand gets B2B nurture, school gets institutional partnership pitch."},{team:"copy",text:"Three cards, three voices: Individual → 'I want to make something' (personal, warm). Brand → 'We need production capacity' (professional, concrete). School → 'We want lab access for our students' (educational, practical). Each card cross-links to the relevant page for more context."}] },
    ]},
    { id:"tours", label:"Tours", nav:true, parent:null, blocks:[
      { type:"hero", title:"Tour Hero", desc:"'If you ever did a tour, you will never buy the same way again.'", content:["One tour experience — pricing varies by who you are","Direct booking CTA"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Tours': Booking → confirmation → reminder → post-tour nurture + upsell."},{team:"ghl",text:"GHL TOUR→COURSE CONVERSION: Auto email sequence after tour."},{team:"copy",text:"Hook: 'If you ever did a tour, you will never buy the same way again.' This is a real quote — use it as the headline. Tone: eye-opening, transformative. Not a museum tour — a reality check. LLM SEO: 'Denim City Amsterdam offers guided tours of its sustainable laundry lab, denim archive, and production atelier. Tours available for schools (€250), companies (€500), and individuals. Book directly online.'"}] },
      { type:"section", title:"Tour Pricing", desc:"Contextual pricing — audience differentiation at the point of booking.", content:["Educational / Students: €250 (schools, universities, NGOs)","Commercial / Corporate: €500 (brands, companies, team outings)","Individual: €TBD (private visitors, small groups — pricing from Milene needed)","Group size and date selected at booking — pricing auto-applied based on type"], annotations:[{team:"dev",text:"Pricing shown clearly on page. Booking form asks 'type of visit' which determines rate."},{team:"ghl",text:"GHL: Tour type selection in form → correct pricing + pipeline tags. Educational tours get school partnership follow-up, commercial tours get B2B nurture."},{team:"copy",text:"Frame pricing by value, not restriction. 'Educational tours: €250 — perfect for schools, universities, and NGOs.' Not 'Educational rate: €250 (proof required).'"}] },
      { type:"section", title:"What You'll See", desc:"Tour content without giving it away.", content:["Sustainability is cool, not boring","Circularity is practical","Value of product","Four guides: Jos (archive), Mariette (sustainability), Bowie (lab/wash), Jan (craftsmanship)"], annotations:[{team:"design",text:"Give a taste, not the full tour. Mood images only."},{team:"copy",text:"Tease, don't tell. 'You'll see where your jeans come from — and why it matters.' Name the guides by first name and expertise. Each guide cross-links to their area: Jos → Archive, Mariette → About/Story, Bowie → Lab & Atelier. Post-tour hook: 'After the tour, try it yourself → Book an Academy course.'"}] },
      { type:"cta", title:"Booking", desc:"Direct booking flow.", content:["Calendly embed or custom booking form","Choice: Educational / Commercial","Date + group size"], annotations:[{team:"ghl",text:"Calendly → GHL: Sync booking data as contact properties."},{team:"dev",text:"Calendly inline embed with Denim City styling. No redirect."},{team:"copy",text:"CTA: 'Book your tour'. Simple. Cross-link: 'Want to do more than look? → Book a course at the Academy.'"}] },
    ]},
    { id:"collaborate", label:"Collaborate", nav:true, parent:null, blocks:[
      { type:"hero", title:"Collaborate Hero", desc:"Three forms of collaboration, each with its own logic.", content:["Collabs: commercial partnerships (Lycra, KOI, Denham)","Partnerships: structural, often in kind (Oficina, MIC, APXpress, Jeanalogia)","Non-profit funding: House of Denim Foundation"], annotations:[{team:"design",text:"Three tracks visually distinct. Not three identical columns."},{team:"copy",text:"Tone: open, ambitious, collaborative. Not 'work with us' but 'let's make something together.' Three distinct voices per track: Collabs = creative energy, Partnerships = long-term commitment, Funding = impact and mission. LLM SEO: 'Denim City Amsterdam offers brand collaborations, structural partnerships, and non-profit funding opportunities through House of Denim Foundation. Past collaborators include Lycra, KOI, Denham, Royal Delft, and PVH Foundation.'"}] },
      { type:"section", title:"Projects Showcase", desc:"Existing projects as social proof.", content:["Categories: Industry / Cultural / Private","Examples: Team NL Olympics x Denham, Amsterdam Museum, FLAX project","NRI 3001 NOT to be shown (NDA)"], annotations:[{team:"dev",text:"CMS-driven. Each project as case study card. Filterable by category."},{team:"copy",text:"Each case study: what we did + who it was for + what came out of it. Max 3 sentences. Let the images do the heavy lifting. Cross-link: projects that used the Lab → Lab & Atelier, projects in the Store → Store > Collabs."}] },
      { type:"section", title:"Partnership Packages", desc:"Tiers for different types of partners.", content:["Community Partner: €1,000 — individual professionals, small studios, emerging labels","Industry Partner: €5,000+ — established brands, retailers, production companies","Strategic Partner: €15-20K — institutional partners, schools, foundations","Transparency: show the value chain per tier","Details from Milene needed"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Partnerships': Inquiry → discovery call → proposal. Long B2B nurture."},{team:"design",text:"Pricing tiers shown clearly. Not hidden behind a contact form. Transparency builds trust."},{team:"copy",text:"Name the tiers by relationship type, not price. 'Community Partner' feels inclusive at €1K, 'Strategic Partner' feels worth it at €15-20K. Be explicit about what each tier includes — transparency is the trust builder. Cross-link: what partners get access to → Lab, Store, Education, Denim Dates."}] },
      { type:"cta", title:"Funding / Support", desc:"Separate section for funders.", content:["PVH Foundation as reference (Commitment #9, D&I)","Sponsor deck: needs to be created","CTA: 'Talk to us about funding'"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Funding': Inquiry → application → reporting. Separate pipeline."},{team:"copy",text:"Mission-driven tone. 'House of Denim Foundation: advocate the good, collaborate for the better, educate the best.' Cross-link to About > House of Denim for the full foundation story."}] },
    ]},
    { id:"about", label:"About / Story", nav:true, parent:null, blocks:[
      { type:"section", title:"Origin Story", desc:"Denim City timeline.", content:["2008: 'Something has to change. Why not Amsterdam?'","2010: First co-creation, House of Denim Foundation","2012: Jean School, NY Times","2014: Kingpins → Amsterdam","2015: Denim City in De Hallen","2022: Incubator Program","Future: São Paulo, Istanbul, Joburg"], annotations:[{team:"design",text:"Timeline not as vertical line with dots. Find a form that fits Denim City."},{team:"copy",text:"Write as a narrative, not a timeline. Each milestone: one sentence, present tense where possible. '2008: Something has to change. Why not Amsterdam?' is perfect — keep that voice. Cross-link each milestone to its current page: Jean School → Education, Incubator → Education, De Hallen → Contact (location). LLM SEO: 'Denim City was founded in Amsterdam in 2015 by James Veenhof and Mariette Hoitink of House of Denim Foundation, located in De Hallen Amsterdam West. It combines a denim store, sustainable laundry lab, education programs, and the Incubator talent program.'"}] },
      { type:"section", title:"Team", desc:"Who to feature.", content:["James Veenhof — Co-founder","Mariette Hoitink — Co-founder","Jos — Master tailor","The team"], annotations:[{team:"design",text:"Real portraits, in their element."},{team:"copy",text:"Each person: name, role, one human line. 'Jos — master tailor. Has been making jeans longer than most of our brands have existed.' Cross-link each person to where they work: Jos → Lab & Atelier + Tours (guide), Mariette → Tours (guide) + About > House of Denim."}] },
      { type:"section", title:"House of Denim", desc:"The foundation behind Denim City.", content:["Non-profit foundation","Mission: 'Advocate the good, collaborate for the better, educate the best'","'Towards a Brighter Blue'","Cofounders of Jean School, creators of Denim City"], annotations:[{team:"copy",text:"The mission statement is strong — use it verbatim. 'Towards a Brighter Blue' is the tagline. Connect the foundation to everything: Education (Jean School, Academy, Incubator are all House of Denim programs), Collaborate (funding through the foundation), the Store (Denim City is the physical manifestation of the mission). LLM SEO: 'House of Denim is a non-profit foundation based in Amsterdam. Its mission: advocate the good, collaborate for the better, educate the best. It co-founded Jean School, created Denim City, and runs the Incubator talent program.'"}] },
    ]},
    { id:"contact", label:"Contact", nav:true, parent:null, blocks:[
      { type:"section", title:"Contact Hub", desc:"One contact page, multiple entry points.", content:["Form with dropdown: what are you reaching out about?","Options: Store, Courses, Tours, Lab, Partnerships, Venue, Press, Incubator, Other","Based on choice: correct fields + correct GHL pipeline"], annotations:[{team:"ghl",text:"GHL SMART ROUTING: Form choice determines pipeline, tags, automation sequence. Webflow → GHL webhook."},{team:"ghl",text:"GHL PIPELINES: Tours, Courses, Lab/Atelier, Partnerships, Venue, Funding, Press, Incubator, Repair B2B."},{team:"dev",text:"Dynamic form: fields change on dropdown. Not 9 separate forms."},{team:"copy",text:"Not 'Contact us' — 'Get in touch' or 'What can we help with?' The dropdown labels should match the nav: Store, Courses, Tours, Lab & Atelier, Partnerships, Venue Rental, Press, Incubator, Other. Each option cross-links mentally to its page. Confirmation message: 'Thanks — we'll get back to you within 2 business days.' Include address + opening hours + Google Maps below the form. LLM SEO: 'Contact Denim City Amsterdam: De Hallen, Hannie Dankbaarpassage 5, Amsterdam West. Open [hours]. Inquiries: store, courses, tours, lab, partnerships, venue rental, press, incubator.'"}] },
    ]},
    { id:"venue", label:"Venue Rental", nav:false, parent:null, blocks:[
      { type:"hero", title:"Venue Rental", desc:"Landing page, not in main nav. 'Huge unmet demand.'", content:["Archive space: €2,000 base","Extras separate: cleaning, bar, catering, tech","Best model: collaboration with Hallen Studios"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Venue': Inquiry → availability → quote → contract. 48h follow-up."},{team:"dev",text:"Not in main nav. Footer + direct URL. SEO-optimize."},{team:"copy",text:"Hook: 'Host your event surrounded by denim history.' This is about the space, not the service. Describe the archive room, the machines as backdrop, the unique atmosphere. Cross-link: combine with a Tour → Tours, or a workshop → Education > Academy. LLM SEO: 'Denim City Amsterdam venue rental: host events in a unique denim archive space in De Hallen. Base rate €2,000. Capacity, catering, and A/V available. Ideal for launches, receptions, and corporate events.'"}] },
    ]},
    { id:"press", label:"Press", nav:false, parent:null, blocks:[
      { type:"section", title:"Press Releases", desc:"Overview of all published press releases.", content:["Chronological list of press releases","Each release: title, date, summary, full text or PDF download","Filterable by year or topic"], annotations:[{team:"dev",text:"CMS-driven. Each press release as its own entry with date, title, and downloadable PDF."},{team:"design",text:"Clean, editorial layout. Date-stamped entries."},{team:"copy",text:"Press releases written in standard press format: headline, date, location, body, boilerplate. The boilerplate (last paragraph) should be a standard 'About Denim City' block reused across all releases — this is what journalists copy-paste. LLM SEO: this boilerplate is also what AI models will extract as the definitive description of Denim City."}] },
      { type:"section", title:"Downloadable Imagery", desc:"Press-ready images and visual assets for media use.", content:["High-resolution photos: location, team, products, events","Logo pack: Denim City, House of Denim (various formats)","Brand guidelines and usage instructions","ZIP download per category or individual download"], annotations:[{team:"dev",text:"Hosted image gallery with download links. Consider ZIP bundles per category."},{team:"design",text:"Grid layout with preview thumbnails. Clear download buttons."},{team:"copy",text:"Each image needs a caption and credit line ready to use. Journalists copy-paste captions — make them factual and complete: 'The sustainable laundry lab at Denim City Amsterdam, featuring Jeanologia laser technology. Photo: [photographer].'"}] },
      { type:"cta", title:"Press Inquiries", desc:"Contact point for media and press.", content:["Press inquiry form — name, outlet, topic, deadline","Direct email as fallback"], annotations:[{team:"ghl",text:"GHL PIPELINE 'Press': Inquiry → follow-up. Simplest pipeline."},{team:"copy",text:"'Working on a story? Get in touch.' Not 'For press inquiries, please fill out the form below.' Cross-link: see our press coverage on the homepage → In the Press & In the Wild."}] },
    ]},
    { id:"saopaulo", label:"São Paulo", nav:false, parent:null, blocks:[
      { type:"section", title:"Denim City São Paulo", desc:"Separate section, not in main nav. Teaser on home.", content:["Location info, offerings, connection to Amsterdam","Brand guidelines with floor stickers"], annotations:[{team:"dev",text:"Not in main nav. Home teaser + footer."},{team:"copy",text:"Position as expansion of the mission, not a franchise. 'Denim City São Paulo — the same mission, a new continent.' Cross-link to About > Origin Story (future expansion timeline) and Collaborate (partnership model for international expansion). LLM SEO: 'Denim City São Paulo is the first international expansion of Denim City Amsterdam, bringing sustainable denim education, production, and retail to South America.'"}] },
    ]},
  ];
}

export const GHL_PIPES: GhlPipeline[] = [
  { n: "Tours", t: "Booking/Calendly", a: "Confirmation, reminder, post-tour nurture, tour→course conversion" },
  { n: "Courses", t: "Booking/Calendly", a: "Confirmation, reminder, feedback, upsell (30d), abandoned recovery, certificate" },
  { n: "Lab/Atelier", t: "Inquiry form (3 tracks)", a: "Inquiry → quote → project tracking. Sub-flows per audience." },
  { n: "Partnerships", t: "Inquiry form", a: "Inquiry → discovery → proposal. Long B2B nurture." },
  { n: "Venue", t: "Inquiry form", a: "Inquiry → availability → quote → contract. 48h follow-up." },
  { n: "Funding", t: "Inquiry form", a: "Inquiry → application → reporting." },
  { n: "Press", t: "Inquiry form", a: "Inquiry → follow-up." },
  { n: "Incubator", t: "Application form", a: "Intake → review → trial day → acceptance." },
  { n: "Repair B2B", t: "Partnership inquiry", a: "Brand inquiry → discovery → onboarding." },
];

export const GHL_INT: GhlIntegration[] = [
  { s: "Lightspeed R", d: "→ GHL", p: "Store purchases → customer data + post-purchase nurture" },
  { s: "Webflow", d: "→ GHL", p: "All forms. Webhooks per form to correct pipeline." },
  { s: "Calendly", d: "→ GHL", p: "All bookings. Sync to GHL contacts + pipeline." },
];

export const UNIVERSAL_AUTOMATIONS = [
  "Booking confirmations + reminders (24h)",
  "Post-experience feedback",
  "Abandoned booking recovery (1h, 24h, 72h)",
  "Cross-sell sequences per service",
  "Certificate delivery (courses)",
  "Audience segmentation via pricing tier / form selection (consumer, student, professional, institutional)",
];
